#!/usr/bin/env php
<?php
// Vendor autoload
$autoloadpaths = [
  __DIR__ . '/vendor/autoload.php',
  __DIR__ . '/../../autoload.php',
];
$autoloaded = false;

foreach ($autoloadpaths as $path) {
  if (file_exists($path)) {
    require $path;
    $autoloaded = true;
    break;
  }
}

if (!$autoloaded) {
  echo 'ERROR: Composer autoload.php could not be found.' . PHP_EOL;
  exit(1);
}

use Gwa\Wpsh\Command\MysqlDumpCommand;
use Gwa\Wpsh\Command\MysqlSyncCommand;
use Gwa\Wpsh\Command\RsyncCommand;
use Gwa\Wpsh\Command\ShowAliasesCommand;
use Symfony\Component\Console\Application;

// Create application
$application = new Application;

// Register commands
$application->add(new MysqlDumpCommand);
$application->add(new MysqlSyncCommand);
$application->add(new RsyncCommand);
$application->add(new ShowAliasesCommand);

$application->run();
